### ISSUE TITLE
INTRODUCTION TO OPEN SOURCE | NAIROBI - 2021/06/12

### ISSUE THREAD

**Issue by veldakarimi** [oscafrica/chapter-leads-hub#21] opened 2021-05-22 04:39 UTC
> Before you start, please follow the issue title format and assign yourself to this issue.

> If the event is a multiple date event, only add the starting date in the title.

> Please note that we need **2 weeks minimum and 3 weeks maximum notice** to approve proposed events.

> Please note that we need **21 days maximum notice** to provide support from your request.

## Event information
_Please complete all applicable._

- **Event name**: Introduction to Open Source
- **Event date**: _2021/06/12_
- **Estimated number of attendees**: 30 - 60
- **Event location**: Nairobi
- **Event description**: The event will offer a brief introduction to Open Source, opportunities available among other benefits and how to start contributing to Open Source. As well as spotlight Open Source Projects that are building for Africa.

## How does this benefit your chapter?
_This will benefit our community because they will get to know the various ways of contributing to open source, become aware of different open source projects that are building for Africa, as well as understand the benefits of Open Source._

## What help do you need with this event? 
_The event is going to be online. The help we need is for the event to be created on OpenCollective._

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [X] You have completed the [request form](https://bit.ly/osca-cl-request) for sponsorship.

**Before the event**: 
- [X] Your event is approved.
- [X] Your event's RSVP page has been created on [Open Collective](https://opencollective.com/osca).
- [X] You have received your sponsorship (if requested).

**After the event**:  
- [X] You have completed the [post-event report](/docs/post-event-template.md).
- [X] You have submitted all related expense receipts for this event.
- [ ] This issue is closed.

**Comment by veldakarimi** [comment] 2021-05-22 04:50
Hey @BolajiAyodeji 
I did not add labels because I was not allowed to.
I Would also like to request you to look into this.

**Comment by BolajiAyodeji** [comment] 2021-05-23 21:43
Hi @veldakarimi, thanks for submitting this issue.

Yes, we're aware of your inability to add labels to issues currently, and we're working to resolve this next week. Apologies for any inconvenience that this might have caused you.

Your event looks good to me; great work! Please go ahead and start making the necessary arrangements. We would create your event page on Open Collective and get back to you. Do share with us your event flyer if you have any as soon as possible.

Looking forward to your post-event report, cheers!

**Comment by BolajiAyodeji** [comment] 2021-05-24 04:10
Hi @veldakarimi, here's your event link: https://opencollective.com/osca/events/osca-nairobi-introduction-to-open-source-af95b184. Your attendees can register using the free **Attendee ticket**.

Kindly let us know the actual time of the event, thank you!

**Comment by veldakarimi** [comment] 2021-05-24 04:42
The actual time of the event is 2pm to 4pm EAT.
I will be sharing with you the poster soon

**Comment by BolajiAyodeji** [comment] 2021-05-24 06:56
Time changed! Thank you, and good luck with your event.

**Comment by veldakarimi** [comment] 2021-05-24 08:49
I wanted to ask if for example our event is going to be streamed to YouTube
will the link be sent to the attendee list?

**Comment by BolajiAyodeji** [comment] 2021-05-24 09:22
We can send an email to your attendees for you or export your attendee's list and share it with you. Does that work for you?

**Comment by BolajiAyodeji** [comment] 2021-05-24 09:27
You can email your attendees with the link to your stream via a special email. I'll communicate that to you privately; thanks!

**Comment by veldakarimi** [comment] 2021-05-24 18:44
okay, since we plan on streaming it can the number of tickets be increased to 150?

**Comment by BolajiAyodeji** [comment] 2021-05-24 19:29
Done, thank you!

**Comment by veldakarimi** [comment] 2021-05-25 19:46
Hey @BolajiAyodeji I just realized the time indicated has an error, it says 4pm to 6pm instead of 2pm to 4pm

**Comment by BolajiAyodeji** [comment] 2021-05-25 20:08
Hi @veldakarimi,

Sorry about that; it looks like a timezone conflict. We have fixed that now, thank you!

**Comment by veldakarimi** [comment] 2021-06-05 18:34
Hi @BolajiAyodeji
Here is our poster for our event.

Best Regards,
Velda Kiara

**Comment by BolajiAyodeji** [comment] 2021-06-05 19:44
Hi @veldakarimi, I'm not sure you attached an image in your message.

**Comment by veldakarimi** [comment] 2021-06-06 04:39
![IMG-20210603-WA0009](https://user-images.githubusercontent.com/32552296/120912714-53e96500-c69a-11eb-9884-0a40f56507c6.jpg)

**Comment by veldakarimi** [comment] 2021-06-10 13:41
Hey @BolajiAyodeji 
We noticed on the button where there is RSVP  that it has a grammatical error. 
And I also wanted to know if I should send the link  so that you can send it to  the attendees for them to be able to access the event or how can we go about this? Our event is on Saturday

**Comment by BolajiAyodeji** [comment] 2021-06-10 16:59
Hi @veldakarimi, thanks for reaching out!

The typographical error is a bug from Open Collective; I'll report this to them. Thanks!

I'm not sure I understand your second question. You want to send the link to me so I can send it to your attendees?

**Comment by veldakarimi** [comment] 2021-06-11 05:26
Hello,
So the second question is more of how we will send the link to the
attendees so when the time comes they are able to access the event.

**Comment by veldakarimi** [comment] 2021-06-11 14:46
Hey @BolajiAyodeji 
The link to the event is: https://www.youtube.com/watch?v=79LvAjEoLbg

**Comment by BolajiAyodeji** [comment] 2021-06-11 19:31
> Hey @BolajiAyodeji
> The link to the event is: https://www.youtube.com/watch?v=79LvAjEoLbg

Hi @veldakarimi, I'll DM you with instructions; thanks.

**Comment by veldakarimi** [comment] 2021-06-12 04:45
Good morning,
I have not seen any instructions yet 😇.

**Comment by BolajiAyodeji** [comment] 2021-06-12 05:50
Hi @veldakarimi, blessed morning.

Kindly check your Discord chat, thanks!

**Comment by veldakarimi** [comment] 2021-06-12 07:03
We have sent the email

**Comment by veldakarimi** [comment] 2021-06-13 00:47
Hi @BolajiAyodeji we have already hosted the event.
There is an issue with the event report, the page cannot be found.

**Comment by BolajiAyodeji** [comment] 2021-06-13 05:52
Hi @veldakarimi, what link are you trying to use to access the post event report template?

**Comment by veldakarimi** [comment] 2021-06-13 05:54
I am using the one on GitHub where it has the links for what to do before
the event, during the event and after the event. The one that we are
supposed to check on the issue.

**Comment by BolajiAyodeji** [comment] 2021-06-13 06:30
Apologies, the issue is fixed now. You can access it here: https://github.com/oscafrica/chapter-leads-hub/blob/master/docs

Cheers!

**Comment by veldakarimi** [comment] 2021-06-13 08:55
# Post Event Report [Introduction to Open Source ] [12/06/21]
## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_The attendance was diverse we had a few ladies, and most people were from Nairobi. We had a total of 67 RSVPs and we had  70 people who joined our live stream.

## Event Venue 🟣

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_
We used stream yard which was good since it allowed us to stream to a wider audience.

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_

_Feel free to share your positive and negative experiences here with bullet points._
- A challenge we had was on the back and forth with using open collective. But we also found out that the chapter has access to a meetup page so its sustainable and we can easily use meetup for our future events.
- We got a few complaints from our attendees on the platform but it will be sorted out since we are now free to use other forms like Google forms. Though I would like to suggest if its possible for us to use meetup instead since we have access.
 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_
- I learned that the attendees are definitely looking to getting into more activities surrounding open source and we as the Nairobi team are excited to bring all this into action.
- I also learned that we need to be more active on discord and telegram and increase our online prescence.
## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._
- The feedback we got was from the comment section. Which was positive.
*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 

## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform_
- https://twitter.com/osca_nairobi/status/1403676839999070211?s=20
- https://twitter.com/wayne_gakuo/status/1403674948703510528?s=20
- https://twitter.com/wayne_gakuo/status/1403670748405846016?s=20
- https://twitter.com/osca_nairobi/status/1403674590807789571?s=20
- https://twitter.com/osca_nairobi/status/1403265164548452352?s=20

## Event Photos 🟢

_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_
The event was online and we did not get the opportunity to take screenshots. But I will include them later on.
## Summary 🟡

_Generally, what's your overview of the event?_
-Being the first event, it was really good and fun.  And we cannot wait to have another event.
_How did it go for you as a Chapter Lead?_
-It went really well, we all talked about our experiences.
_Looking forward to the next event? What changes will you be making based on your experience from this event?_
-Changes are definitely use meetup for our members to RSVP.
-Heavily advertise our event.

**Comment by BolajiAyodeji** [comment] 2021-06-17 11:33
Hi @veldakarimi,

Thanks for the very detailed post-event report; your event was great! We're glad that everything went well, and we look forward to more. About your meetup.com proposal, I have sent you a DM responding to this, and we will issue a memo to all Chapter Leads with guidelines for this.

Great work!

**Closed by BolajiAyodeji** 2021-06-17 11:33 UTC
Labels: Approved ✅, Nairobi, Reviewed
